variables:
 master_branch: refs/heads/feature/pretendMaster
 master_tag: prerelease

trigger:
  branches:
    include:
      - master
      - feature/*
      - bugfix/*
    exclude:
      - azure-pipelines
    


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo tag=$MASTER_TAG
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- checkout: self
  clean: true
  persistCredentials: true

- script: echo "registry=https://registry.npmjs.org/" > .npmrc
  displayName: "create npmrc"

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
    customEndpoint: 'npmjs.org'

- script: |
    git config user.email pipeline@dev.azure.com
    git config user.name build-pipeline
    VERSION=`npm version prerelease --no-git-tag-version --preid=beta`
    while git rev-parse "$VERSION" >/dev/null 2>&1; do
      VERSION=`npm version prerelease --no-git-tag-version --preid=beta`
    done
    echo "Version: $VERSION"
    git tag $VERSION
  displayName: 'increment version'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], variables.master_branch))

- script: |
    git config user.email pipeline@dev.azure.com
    git config user.name build-pipeline
    VERSION=`node -p "require('./package.json').version"`
    echo "Version: $VERSION"
    git tag -f $VERSION
  displayName: tag $(master_tag) version
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], variables.master_branch))

- script: |
    npm install
    npm run build
  displayName: 'npm install'

- script: |
   npm run build
  displayName: 'npm build'

- script: |
    npm run test
  displayName: 'npm test'

- script: npm publish --tag=beta
  displayName: 'npm publish beta'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], variables.master_branch))

- script: npm publish --tag=$MASTER_TAG
  displayName: npm publish $(master_tag)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], variables.master_branch))

- script: |
    git push --tags
  displayName: 'push to GitHub'