# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- feature/*
- bugfix/*


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- checkout: self
  clean: true
  persistCredentials: true

- script: echo "registry=https://registry.npmjs.org/" > .npmrc
  displayName: "create npmrc"

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
    customEndpoint: 'npmjs.org'

- script: |
    git config user.email pipeline@dev.azure.com
    git config user.name build-pipeline
    VERSION=`npm version prerelease --no-git-tag-version --preid=beta`
    while git rev-parse "$VERSION" >/dev/null 2>&1; do
      VERSION=`npm version prerelease --no-git-tag-version --preid=beta`
    done
    echo "Version: $VERSION"
    git tag $VERSION
  displayName: 'increment version'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: |
    npm install
    npm run build
  displayName: 'npm install'

- script: |
   npm run build
  displayName: 'npm build'

- script: |
    npm run test
  displayName: 'npm test'

- script: |
    git push --tags
  displayName: 'push to GitHub'

- script: npm publish --tag=beta
  displayName: 'npm publish beta'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: npm publish
  displayName: 'npm publish latest'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
